### ISSUE TITLE
x/text: potential Go vuln in go/src/crypto/internal/edwards25519/field/_asm/go.sum/golang.org\x\text@v0.3.0

### ISSUE THREAD

**Issue by KumarJayanti** [golang/vulndb#1094]
### Description

Component Paths
go1.19.2.linux-amd64.tar.gz/go/src/crypto/internal/edwards25519/field/_asm/go.sum/golang.org\x\text@v0.3.0
usr/local/go/src/crypto/internal/edwards25519/field/_asm/go.sum/golang.org\x\text@v0.3.0

CVSS Info | CWE | CVE Fix Version | Priority
-- | -- | -- | --
CVE-2020-14040 | 835 | - | P1
CVE-2021-38561 | 125 | - | P3
CVE-2022-32149 | 772 | - | P1

CVSS Info	CWE	CVE Fix Version	Priority
[CVE-2020-14040](http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-14040)	[835](https://cwe.mitre.org/data/definitions/835.html)	-	P1
[CVE-2021-38561](http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-38561)	[125](https://cwe.mitre.org/data/definitions/125.html)	-	P3
[CVE-2022-32149](http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-32149)	[772](https://cwe.mitre.org/data/definitions/772.html)	-	P1

Current Version : V0.3.0, Component Fix Version. : V0.3.8

### Affected Modules, Packages, Versions and Symbols

```shell
Module: github.com/example/module
Package: github.com/example/module/package
Versions:
  - Introduced: 1.2.0
  - Fixed: 1.2.4
Symbols:
  - aFunction
  - SomeType.AMethod

Module: github.com/example/module/v2
Package: github.com/example/module/v2/package
Versions:
  - Fixed: 2.4.5
Symbols:
  - anotherFunction
```

### Does this vulnerability already have an associated CVE ID?

Yes

### CVE ID

CVE-2022-32149

### CWE ID

772

**Comment by neild** [comment]
Thanks for the report.

These CVEs are all for the `golang.org/x/text` module. I'm not quite certain what you're reporting, but I'm guessing you're pointing out that the `src/crypto/internal/edwards25519/field/_asm/go.sum` file contains references to vulnerable versions of `golang.org/x/text`.

This `go.sum` file is associated with a code generator used to build some assembly files. The code generator and its transitive dependencies do not rely on the `golang.org/x/text` module. I believe `x/text` appears in the `go.sum` because there are modules in the transitive dependency set that contain packages that depend on `x/text`, even though no packages in the transitive dependencies depend on `x/text`.

In general, the presence of a module version in `go.sum` is not a reliable signal as to whether a program currently depends on that module; the `go.mod` file is the correct source of dependency information.
