### ISSUE TITLE
x/vulndb: suggestion regarding GO-2022-0646

### ISSUE THREAD

**Issue by oliverchang** [golang/vulndb#1128]
### Report ID

GO-2022-0646

### Suggestion/Comment

The current OSV entry for GO-2022-0646 implies all versions are affected (https://vuln.go.dev/ID/GO-2022-0646.json):

https://github.com/golang/vulndb/blob/750d137f0f230d789a655f6625db398b00bd8ad2/data/osv/GO-2022-0646.json#L23

This does not appear to be the case per the fix commit linked: https://github.com/aws/aws-sdk-go/commit/ae9b9fd92af132cfd8d879809d8611825ba135f4

The vulnerability was fixed in 1.34.0.

**Comment by tatianab** [comment]
In this case, the vulnerable API ([EncryptionClient](https://pkg.go.dev/github.com/aws/aws-sdk-go@v1.44.146/service/s3/s3crypto#EncryptionClient)) was deprecated and users were encouraged to move to [EncryptionClientV2](https://pkg.go.dev/github.com/aws/aws-sdk-go@v1.44.146/service/s3/s3crypto#EncryptionClientV2). But because the vulnerable API still exists, and the fix is to use the new API in addition to upgrading, we intentionally did not mark the vulnerability as fixed in 1.34.0.
