### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/ylck/aws-lambda-go-api-proxy

### ISSUE THREAD

**Issue by sourabh-shinde** [golang/vulndb#1858]
### Description

Etcd Vulnerable to DNS Rebinding Attack Due to Empty HostWhitelist Allowing Any Hostname

### Description
Etcd contains a flaw allowing a DNS rebinding attack. An attacker could exploit this to carry out a client-side attack elsewhere on the network. This vulnerability impacts the confidentiality, integrity and availability of the vulnerable etcd server and is caused by a missing hostname whitelist, allowing the value to be changed.

### Technical Description
This vulnerability allows an attacker to control their own DNS records and can be used to steal sensitive data. Any website can create an authorized DNS name and redirect DNS requests to localhost or any other address. An attacker could exploit this to trick the browser into sending requests to any hostname address. Fixed by adding a `--host-whitelist` flag.

### Vulnerability Source
BDSA

### Affected Modules, Packages, Versions and Symbols

```shell
Module: github.com/coreos
Package: github.com/coreos/go-etcd
Versions:
  - Introduced: v2.0.0

gitlab-master.nvidia.com/gfn/debug/debug-service:-go_mod/github.com/awslabs/aws-lambda-go-api-proxy:v0.14.0/
github.com/kataras/iris/v12:v12.2.0-alpha9/
github.com/dgraph-io/badger/v2:v2.2007.4/
github.com/spf13/cobra:v1.2.1/github.com/spf13/viper:v1.8.1/github.com/coreos/go-etcd:v2.0.0
```

### Does this vulnerability already have an associated CVE ID?

Yes

### CVE ID

BDSA-2018-1028

**Comment by neild** [comment]
Thanks for the report (and sorry for the delay in following up).

This is CVE-2018-1099 and #1448. The Go vulnerability database currently contains only data for importable packages, not every executable program written in Go. Since this vulnerability affects the etcd server, but not any importable packages, we chose to exclude it in #1448.

If you feel that exclusion was in error, please feel free to reopen and comment on #1448. Thanks.

**Comment by neild** [comment]
Duplicate of #1448
