### ISSUE TITLE
x/vulndb: suggestion regarding GO-2022-0965

### ISSUE THREAD

**Issue by sharonbz** [golang/vulndb#1903]
### Report ID

GO-2022-0965

### Suggestion/Comment

This GO vulnerability is related to CVE-2019-11253 in k8s.
See https://github.com/kubernetes/kubernetes/issues/83253 is fixed by https://github.com/kubernetes/kubernetes/pull/83261 which is GO-2022-0965.

**Comment by tatianab** [comment]
Hi @sharonbz, thanks for filing an issue.  GO-2022-0965 already contains a link to CVE-2019-11253 in the references section, but the CVE is not listed as an alias because it is related, but not the same vulnerability. Did you have an additional suggestion for what should be added/modified in this report?

**Comment by sharonbz** [comment]
Ho @tatianab, thanks for the reply. 
I see that https://github.com/kubernetes/kubernetes/pull/83261 is mentioned in the references of GO-2022-0965; however, this is the PR that fixed https://github.com/kubernetes/kubernetes/issues/83253, which is CVE-2019-11253. [k8s.io/apimachinery](https://pkg.go.dev/k8s.io/apimachinery/pkg/util/json) can be affected as well, however, this is not the same vulnerability described in the 2 issues, sourced from the same place?

**Comment by davidsnt** [comment]
@tatianab could you please review the comments from @sharonbz

**Comment by neild** [comment]
Hi, @sharonbz, @davidsnt. I'm afraid I don't follow what you're suggesting or asking.

[GO-2022-0965](https://pkg.go.dev/vuln/GO-2022-0965) describes a vulnerability in the `k8s.io/apimachinery/pkg/runtime/serializer/json` and `k8s.io/apimachinery/pkg/util/json` packages, which was fixed by https://github.com/kubernetes/apimachinery/commit/9ce6eca90e73.

Can you explain in more detail what you'd like to know about this report, or what you think should be changed? Thanks.

**Comment by sharonbz** [comment]
I think that CVE-2019-11253 describes the same vulnerability as [GO-2022-0965](https://pkg.go.dev/vuln/GO-2022-0965), and I suggest to merge them (i.e. mention the CVE as another alias for GO-2022-0965, and add k8s.io/kubernetes/pkg/apiserver as another affected package as mentioned in GHSA-pmqp-h87c-mr78).

As you mentioned,  https://github.com/kubernetes/apimachinery/commit/9ce6eca90 is the fix for GO-2022-0965. This commit refers to another Kubernetes-commit: [8ef4566cefebf49f9a806a36df2105c9149785a1](https://github.com/kubernetes/kubernetes/pull/83261/commits/8ef4566cefebf49f9a806a36df2105c9149785a1) in the kubernetes/kubernetes repository, as a part of the following PR [#83261](https://github.com/kubernetes/kubernetes/pull/83261). 
The description of this PR mentions it fixes https://github.com/kubernetes/kubernetes/issues/83253, which is the reference for CVE-2019-11253. 

Let me know your thoughts. 
Thanks!

**Comment by neild** [comment]
[CVE-2019-11253](https://nvd.nist.gov/vuln/detail/CVE-2019-11253) describes a vulnerability in "the Kubernetes API server". GHSA-pmqp-h87c-mr78 (the GitHub version of this CVE) lists the affected package as "k8s.io/kubernetes/pkg/apiserver". [GO-2022-0965](https://pkg.go.dev/vuln/GO-2022-0965) describes a vulnerability in `k8s.io/apimachinery/pkg/runtime/serializer/json` and `k8s.io/apimachinery/pkg/util/json`, which happens to be the root cause of the apiserver vulnerability. However, the affected scope is different, so I don't believe these are aliases of each other.

The `k8s.io/kubernetes/pkg/apiserver` package imports the affected packages, so there is no need to list it as explicitly affected; dependency analysis (as done by the `govulncheck` tool) can identify the vulnerable dependency.

In adddition, the Go vulnerability database tracks vulnerabilities in importable Go packages, not every program built with Go. The `k8s.io/kubernetes/pkg/apiserver` package is technically importable, but appears to exist solely to build the apiserver binary. It has no importers listed on https://pkg.go.dev/k8s.io/kubernetes/pkg/apiserver and it does not appear to have an API designed for external use. So if a vulnerability existed which affected only this package, it would be out of scope for the vulnerability database.

**Comment by sharonbz** [comment]
@neild Thank you very much for the detailed answer.
However, I wonder - a vulnerability scan on the `k8s.io/kubernetes/pkg/apiserver` package will list both https://github.com/advisories/GHSA-pmqp-h87c-mr78 for this package and [GO-2022-0965](https://pkg.go.dev/vuln/GO-2022-0965) for k8s.io/apimachinery. Wouldn't that be a duplicate? Should I reach out to GHSA to add k8s.io/apimachinery packages to the advisory? Would this be the best approach?

**Comment by neild** [comment]
For what it's worth, https://github.com/advisories/GHSA-74fp-r6jw-h4mp exists as an alias of GO-2022-0965.

It is not uncommon for multiple CVEs to exist for a single root cause--package A has a vulnerability and CVE, project B depends on A and issues a separate CVE covering their project. I don't believe any of the common vulnerability report formats (CVE, OSV, GHSA) have a good way of representing these dependent relationships. In the Go Vulnerability Database, we handle this by issuing a report only for the root cause.

**Comment by tatianab** [comment]
Closing this out for now; feel free to re-open if you have further comments/questions.
