### ISSUE TITLE
x/vulndb: suggestion regarding GO-2024-2550

### ISSUE THREAD

**Issue by nbagnard** [golang/vulndb#2964]
### Report ID

GO-2024-2550

### Suggestion/Comment

The report shows no known fix for this issue which doesn't sound correct.
The affected versions are called out [here](https://nvd.nist.gov/vuln/detail/CVE-2020-7924#range-12205758) :
> 3.6 versions later than 3.6.5; 3.6 versions prior to 3.6.21; 4.0 versions prior to 4.0.21; 4.2 versions prior to 4.2.11; 100 versions prior to 100.2.0. MongoDB Inc. Mongomirror 0 versions later than 0.6.0
The latest version is [100.9.5](https://github.com/mongodb/mongo-tools/releases/tag/100.9.5) and the fix was back-ported to prior versions 3.6, 4.0 and 4.2 too.

Could we get the report updated with this information?

Thank you,
Natacha

**Comment by tatianab** [comment]
Hi, thanks for filing an issue. We have updated the report in https://go.dev/cl/596180.

Note that because the module github.com/mongodb/mongo-tools appears to use its own versioning scheme, the versions mentioned in the source advisory are not recognized by the Go module versioning system. We have added the pseudo-version corresponding with the fix commit as the "fixed" version, and added the versions referenced in the advisory directly to the description of the vulnerability.

Let me know if you'd like to request further edits.
